//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLinker {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectLinker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot create project item with an empty name ähnelt.
        /// </summary>
        internal static string CannotCreateItemWithEmptyName {
            get {
                return ResourceManager.GetString("CannotCreateItemWithEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to create Project Linker output window. ähnelt.
        /// </summary>
        internal static string FailedToCreateOutputWindow {
            get {
                return ResourceManager.GetString("FailedToCreateOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; already exists in the file system. No link was created in target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string FileAlreadyExistsInFileSystem {
            get {
                return ResourceManager.GetString("FileAlreadyExistsInFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linked file &apos;{0}&apos; was removed from target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string FileLinkSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("FileLinkSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The linked file &apos;{0}&apos; was added to target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string FileSuccessfullyLinked {
            get {
                return ResourceManager.GetString("FileSuccessfullyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; is not linked from project &apos;{1}&apos;. No action taken. ähnelt.
        /// </summary>
        internal static string FileToRemoveDoesNotExistInTarget {
            get {
                return ResourceManager.GetString("FileToRemoveDoesNotExistInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder &apos;{0}&apos; was created in target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string FolderCreatedInTarget {
            get {
                return ResourceManager.GetString("FolderCreatedInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder &apos;{0}&apos; was removed from target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string FolderSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("FolderSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder &apos;{0}&apos; in target project &apos;{1}&apos; is not empty, hence it was not removed. ähnelt.
        /// </summary>
        internal static string FolderToRemoveIsNotEmpty {
            get {
                return ResourceManager.GetString("FolderToRemoveIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument &apos;{0}&apos; cannot be empty ähnelt.
        /// </summary>
        internal static string General_ArgumentEmpty {
            get {
                return ResourceManager.GetString("General_ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder &apos;{0}&apos; already exists in the file system. This folder was included in target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string IncludingExistingFolderInProject {
            get {
                return ResourceManager.GetString("IncludingExistingFolderInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing Project Tracker. ähnelt.
        /// </summary>
        internal static string InitializingProjectTracker {
            get {
                return ResourceManager.GetString("InitializingProjectTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid COM Service Provider ähnelt.
        /// </summary>
        internal static string InvalidComServiceProvider {
            get {
                return ResourceManager.GetString("InvalidComServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid name &apos;{0}&apos; for a file ähnelt.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project name &apos;{0}&apos; was not found in the solution. ähnelt.
        /// </summary>
        internal static string InvalidProjectUniqueName {
            get {
                return ResourceManager.GetString("InvalidProjectUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item &apos;{0}&apos; was not linked because it is excluded by the current filters in target project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string ItemExcludedByFilter {
            get {
                return ResourceManager.GetString("ItemExcludedByFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Linker ähnelt.
        /// </summary>
        internal static string LoggerOutputPaneTitle {
            get {
                return ResourceManager.GetString("LoggerOutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project with GUID &apos;{0}&apos; does not exist ähnelt.
        /// </summary>
        internal static string ProjectDoesNotExist {
            get {
                return ResourceManager.GetString("ProjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects are already linked. ähnelt.
        /// </summary>
        internal static string ProjectFilesAlreadyLinked {
            get {
                return ResourceManager.GetString("ProjectFilesAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Linker ähnelt.
        /// </summary>
        internal static string ProjectLinkerCaption {
            get {
                return ResourceManager.GetString("ProjectLinkerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ProjectLinker:  {0} ähnelt.
        /// </summary>
        internal static string ProjectLinkerErrorWithPrefix {
            get {
                return ResourceManager.GetString("ProjectLinkerErrorWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects successfully linked. ähnelt.
        /// </summary>
        internal static string ProjectsSuccessfullyLinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project items successfully linked. ähnelt.
        /// </summary>
        internal static string ProjectsSuccessfullyLinkedAll {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyLinkedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link between target project &apos;{0}&apos;  and source project &apos;{1}&apos; was successfully restored. ähnelt.
        /// </summary>
        internal static string ProjectsSuccessfullyRelinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyRelinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target project &apos;{0}&apos; was successfully unlinked from source project &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string ProjectsSuccessfullyUnlinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyUnlinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target project &apos;{0}&apos; temporarily unlinked from source project &apos;{1}&apos; on Source project closure. ähnelt.
        /// </summary>
        internal static string ProjectsUnlinkedOnSourceClose {
            get {
                return ResourceManager.GetString("ProjectsUnlinkedOnSourceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target project &apos;{0}&apos; temporarily unlinked from source project &apos;{1}&apos; on Target project closure. ähnelt.
        /// </summary>
        internal static string ProjectsUnlinkedOnTargetClose {
            get {
                return ResourceManager.GetString("ProjectsUnlinkedOnTargetClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property &apos;{0}&apos; was not found in the project &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string PropertyNameNotFound {
            get {
                return ResourceManager.GetString("PropertyNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid assembly name &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string ReflectionHelper_InvalidAssemblyName {
            get {
                return ResourceManager.GetString("ReflectionHelper_InvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid qualified name &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string ReflectionHelper_InvalidQName {
            get {
                return ResourceManager.GetString("ReflectionHelper_InvalidQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project &apos;{1}&apos; is already linked to source project &apos;{2}&apos; as a Target. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored. ähnelt.
        /// </summary>
        internal static string SourceProjectIsAlreadyLinkedAsTarget {
            get {
                return ResourceManager.GetString("SourceProjectIsAlreadyLinkedAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String cannot be empty ähnelt.
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project &apos;{0}&apos; is already linked to target project {2} as a Source. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored. ähnelt.
        /// </summary>
        internal static string TargetProjectIsAlreadyLinkedAsSource {
            get {
                return ResourceManager.GetString("TargetProjectIsAlreadyLinkedAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project &apos;{0}&apos; is already linked to source project &apos;{2}&apos; as a Target. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored. ähnelt.
        /// </summary>
        internal static string TargetProjectIsAlreadyLinkedAsTarget {
            get {
                return ResourceManager.GetString("TargetProjectIsAlreadyLinkedAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target project &apos;{0}&apos; is waiting for source project with GUID {1} to be loaded in order to restore its link. ähnelt.
        /// </summary>
        internal static string TargetProjectWaitingForSource {
            get {
                return ResourceManager.GetString("TargetProjectWaitingForSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project kind is unsupported. ähnelt.
        /// </summary>
        internal static string UnsupportedProjectKind {
            get {
                return ResourceManager.GetString("UnsupportedProjectKind", resourceCulture);
            }
        }
    }
}
